/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.ulbra.view;

import br.ulbra.entity.Pesquisa;
import br.ulbra.model.dao.PesquisaDAO;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class FrmPesquisa extends javax.swing.JFrame {

    /**
     * Creates new form FrmPesquisa
     */
    public FrmPesquisa() {
        initComponents();
        setLocationRelativeTo(null);
        readTable();
        btnalterar.setEnabled(false);
        btnexcluir.setEnabled(false);
        
        if (tabela == null){
            btnbuscar.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmasc = new javax.swing.JRadioButton();
        txtfemi = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtidade = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtgrau = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtconta = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtsalario = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        btnalterar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        btncadastrar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pesquisa Senso");

        jLabel2.setText("Nome do Pesquisado: ");

        jLabel3.setText("Sexo:");

        txtsexo.add(txtmasc);
        txtmasc.setText("Masculino");

        txtsexo.add(txtfemi);
        txtfemi.setText("Feminino");

        jLabel4.setText("Idade:");

        txtidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));

        jLabel5.setText("Grau de Instrução:");

        txtgrau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ens. Fundamental (Incompleto)", "Ens. Fundamental (Completo)", "Ens. Médio (Incompleto)", "Ens. Médio (Completo)", "Ens. Superior (Incompleto)", "Ens. Superior (Completo)", "Pós Graduação", "Mestrado", "Doutorado", " " }));

        jLabel6.setText("Possui Conta Corrente:");

        jLabel7.setText("Salario - Faixa Salarial");

        txtsalario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "R$0,00 - R$1000,00", "R$1000,00 - R$2500,00", "R$2500,00 - Acima", "Não Responder" }));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Sexo", "Idade", "Grau", "Conta", "Salario"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMinWidth(40);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabela.getColumnModel().getColumn(0).setMaxWidth(40);
            tabela.getColumnModel().getColumn(2).setMinWidth(75);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(75);
            tabela.getColumnModel().getColumn(2).setMaxWidth(75);
            tabela.getColumnModel().getColumn(3).setMinWidth(45);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(45);
            tabela.getColumnModel().getColumn(3).setMaxWidth(45);
            tabela.getColumnModel().getColumn(5).setMinWidth(80);
            tabela.getColumnModel().getColumn(5).setPreferredWidth(80);
            tabela.getColumnModel().getColumn(5).setMaxWidth(80);
            tabela.getColumnModel().getColumn(6).setMinWidth(80);
            tabela.getColumnModel().getColumn(6).setPreferredWidth(80);
            tabela.getColumnModel().getColumn(6).setMaxWidth(80);
        }

        btnalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/if_90_171449.png"))); // NOI18N
        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/if_ic_delete_48px_352303.png"))); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnlimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/if_broom_stick_3_896656.png"))); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        btncadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/if_save_1608823.png"))); // NOI18N
        btncadastrar.setText("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/if_Rounded-10_2024633.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/if_back-left-arrow-botton_2203523.png"))); // NOI18N
        btnvoltar.setText("Voltar Para Tela Anterior");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        txtid.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtmasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfemi)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtidade, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtgrau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator2)
                            .addComponent(btnvoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtconta)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btncadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnalterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnexcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnlimpar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmasc)
                    .addComponent(txtfemi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtgrau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtconta))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnalterar)
                    .addComponent(btnexcluir)
                    .addComponent(btnlimpar)
                    .addComponent(btncadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnvoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        
        Pesquisa c = new Pesquisa();
        PesquisaDAO cldao = new PesquisaDAO();
        
        c.setNomep(txtnome.getText());
        
        if (txtmasc.isSelected()){
            c.setSexop("Masculino");
        }else{
            c.setSexop("Feminino");
        }
        
        c.setIdadep(Integer.parseInt(txtidade.getSelectedItem().toString()));
                
        c.setGrauip(txtgrau.getSelectedItem().toString());
        
        if (txtconta.isSelected()){
            c.setContap(1);
        }else{
            c.setContap(0);
        }
        
        c.setSalariop(txtsalario.getSelectedItem().toString());
           
        cldao.create(c);

        txtnome.setText("");
        txtconta.setText("");
        txtmasc.setSelected(false);
        txtfemi.setSelected(false);
        txtconta.setSelected(false);
        txtidade.setSelectedIndex(0);
        txtgrau.setSelectedIndex(0);
        txtsalario.setSelectedIndex(0);
            
        
        readTable();
        
        btnalterar.setEnabled(false);
        btnexcluir.setEnabled(false);
        
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
      
        if (tabela.getSelectedRow() != -1) {

            Pesquisa c = new Pesquisa();
            PesquisaDAO cldao = new PesquisaDAO();

            c.setNomep(txtnome.getText());
        
        if (txtmasc.isSelected()){
            c.setSexop("Masculino");
        }else{
            c.setSexop("Feminino");
        }
        
        switch (txtidade.getSelectedIndex()){
            case 0:
                c.setIdadep(14);
            break;
                
            case 1:
                c.setIdadep(15);
            break;
            
            case 2:
                c.setIdadep(16);
            break;
                
            case 3:
                c.setIdadep(17);
            break;
                
            case 4:
                c.setIdadep(18);
            break;
                
            case 5:
                c.setIdadep(19);
            break;
                
            case 6:
                c.setIdadep(20);
            break;
                
            case 7:
                c.setIdadep(21);
            break;
                
            case 8:
                c.setIdadep(22);
            break;
                
            case 9:
                c.setIdadep(23);
            break;
                
            case 10:
                c.setIdadep(24);
            break;
                
            case 11:
                c.setIdadep(25);
            break;
                
            case 12:
                c.setIdadep(26);
            break;
                
            case 13:
                c.setIdadep(27);
            break;
                
            case 14:
                c.setIdadep(28);
            break;
                
            case 15:
                c.setIdadep(29);
            break;
                
            case 16:
                c.setIdadep(30);
            break;
                
            case 17:
                c.setIdadep(31);
            break;
                
            case 18:
                c.setIdadep(32);
            break;
                
            case 19:
                c.setIdadep(33);
            break;
                
            case 20:
                c.setIdadep(34);
            break;
                
            case 21:
                c.setIdadep(35);
            break;
            
            case 22:
                c.setIdadep(36);
            break;
            
            case 23:
                c.setIdadep(37);
            break;
                
            case 24:
                c.setIdadep(38);
            break;
                
            case 25:
                c.setIdadep(39);
            break;
               
            case 26:
                c.setIdadep(40);
            break;
                
            case 27:
                c.setIdadep(41);
            break;
            
            case 28:
                c.setIdadep(42);
            break;
            
            case 29:
                c.setIdadep(43);
            break;
                
            case 30:
                c.setIdadep(44);
            break;
                
            case 31:
                c.setIdadep(45);
            break;
               
            case 32:
                c.setIdadep(46);
            break;
                
            case 33:
                c.setIdadep(47);
            break;
            
            case 34:
                c.setIdadep(48);
            break;
            
            case 35:
                c.setIdadep(49);
            break;
                
            case 36:
                c.setIdadep(50);
            break;
                
            case 37:
                c.setIdadep(51);
            break;
               
            case 38:
                c.setIdadep(52);
            break;
                
            case 39:
                c.setIdadep(53);
            break;
            
            case 40:
                c.setIdadep(54);
            break;
            
            case 41:
                c.setIdadep(55);
            break;
                
            case 42:
                c.setIdadep(56);
            break;
                
            case 43:
                c.setIdadep(57);
            break;
               
            case 44:
                c.setIdadep(58);
            break;
                
            case 45:
                c.setIdadep(59);
            break;
            
            case 46:
                c.setIdadep(60);
            break;
                         
        }
        //JOptionPane.showMessageDialog(null, txtgrau.getSelectedItem().toString());
                
        c.setGrauip(txtgrau.getSelectedItem().toString());
        
        if (txtconta.isSelected()){
            c.setContap(1);
        }else{
            c.setContap(0);
        }
        
        c.setSalariop(txtsalario.getSelectedItem().toString());
        
        c.setId((int) tabela.getValueAt(tabela.getSelectedRow(), 0));
           
        cldao.update(c);

        txtnome.setText("");
        txtconta.setText("");
        txtmasc.setSelected(false);
        txtfemi.setSelected(false);
        txtconta.setSelected(false);
        txtidade.setSelectedIndex(0);
        txtgrau.setSelectedIndex(0);
        txtsalario.setSelectedIndex(0);

            readTable();
        }
        
    }//GEN-LAST:event_btnalterarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        
        if (tabela.getSelectedRow() != -1) {

            Pesquisa c = new Pesquisa();
            PesquisaDAO cldao = new PesquisaDAO();
            
            c.setId((int) tabela.getValueAt(tabela.getSelectedRow(), 0));
           
            cldao.delete(c);

            txtnome.setText("");
            txtconta.setText("");
            txtmasc.setSelected(false);
            txtfemi.setSelected(false);
            txtconta.setSelected(false);
            txtidade.setSelectedIndex(0);
            txtgrau.setSelectedIndex(0);
            txtsalario.setSelectedIndex(0);

            readTable();
            
            btnalterar.setEnabled(false);
        btnexcluir.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        
        txtnome.setText("");
        txtconta.setText("");
        txtmasc.setSelected(false);
        txtfemi.setSelected(false);
        txtconta.setSelected(false);
        txtidade.setSelectedIndex(0);
        txtgrau.setSelectedIndex(0);
        txtsalario.setSelectedIndex(0);
        
        btnalterar.setEnabled(false);
        btnexcluir.setEnabled(false);
        btncadastrar.setEnabled(true);
        btnbuscar.doClick();
        
    }//GEN-LAST:event_btnlimparActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
       
        readJTableForDesc(txtbuscar.getText());
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
       
        new FrmPrincipal().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        
        String sexo,grau,sal;
        
        int idade=14,conta;
        
        if (tabela.getSelectedRow() != -1) {

            txtid.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            txtnome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            
            sexo = tabela.getValueAt(tabela.getSelectedRow(), 2).toString();
            
            if(sexo.equals("Masculino")){
                txtmasc.setSelected(true);        
            }else{
                txtfemi.setSelected(true);   
            }
            
            txtidade.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
                                  
            grau = tabela.getValueAt(tabela.getSelectedRow(), 4).toString();
            
            if(grau.equals("Ens. Fundamental (Incompleto)")){
                txtgrau.setSelectedItem("Ens. Fundamental (Incompleto)");
                
            }if(grau.equals("Ens. Fundamental (Completo)")){               
                txtgrau.setSelectedItem("Ens. Fundamental (Completo)");
                
            }if(grau.equals("Ens. Médio (Incompleto)")){               
                txtgrau.setSelectedItem("Ens. Médio (Incompleto)");
                
            }if(grau.equals("Ens. Médio (Completo)")){               
                txtgrau.setSelectedItem("Ens. Médio (Completo)");
                
            }if(grau.equals("Ens. Superior (Incompleto)")){               
                txtgrau.setSelectedItem("Ens. Superior (Incompleto)");
                
            }if(grau.equals("Ens. Superior (Completo)")){               
                txtgrau.setSelectedItem("Ens. Superior (Completo)");
                
            }if(grau.equals("Pós Graduação")){               
                txtgrau.setSelectedItem("Pós Graduação");
                
            }if(grau.equals("Mestrado")){               
                txtgrau.setSelectedItem("Mestrado");    
                
            }if(grau.equals("Doutorado")){
                txtgrau.setSelectedItem("Doutorado");
            }
            
            conta = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 5) .toString());
            
            if(conta == 1){
                txtconta.setSelected(true);        
            }else{
                txtconta.setSelected(false);   
            }
            
            txtsalario.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
            
        }
        
        btnalterar.setEnabled(true);
        btnexcluir.setEnabled(true);
        btncadastrar.setEnabled(false);
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    public void readTable() {
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        PesquisaDAO cldao = new PesquisaDAO();
        for (Pesquisa c : cldao.read()) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNomep(),
                c.getSexop(),
                c.getIdadep(),
                c.getGrauip(),
                c.getContap(),
                c.getSalariop()});

        }
    }

    public void readJTableForDesc(String desc) {

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        PesquisaDAO cldao = new PesquisaDAO();

        for (Pesquisa c : cldao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                c.getId(),
                c.getNomep(),
                c.getSexop(),
                c.getIdadep(),
                c.getGrauip(),
                c.getContap(),
                c.getSalariop()});

        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JCheckBox txtconta;
    private javax.swing.JRadioButton txtfemi;
    private javax.swing.JComboBox txtgrau;
    private javax.swing.JTextField txtid;
    private javax.swing.JComboBox txtidade;
    private javax.swing.JRadioButton txtmasc;
    private javax.swing.JTextField txtnome;
    private javax.swing.JComboBox txtsalario;
    private javax.swing.ButtonGroup txtsexo;
    // End of variables declaration//GEN-END:variables
}
